### PR TITLE
Listening History (end-to-end)

### PR DESCRIPTION
**Pull request by Jma353**
Creation / update: 
create-update

Get (paginated):
get

Deletion: 
deletion

Clear (delete all history): 
clear

### CODE REVIEW

**Comment by Jma353** [comment]
@kevingreer @ChenJesse feel free to review.  Apologies for the weird commit structure, things got out of whack when rebasing.

**Comment by kevingreer** [comment]
The create and delete endpoints don't include the episode in the response

**Comment by Jma353** [comment]
@kevingreer Do we need it?  Is that necessary for client?  I noticed that but intentionally left it out if we aren't doing anything meaningful with it in the POST / DELETE request

**Comment by Jma353** [comment]
ping

**Comment by kevingreer** [comment]
No we don't need to include the episode in create or delete requests. As far as I know the client does not use it, nor does it use it for any other kind of create or delete request

**Review by kevingreer — APPROVED** [review]

**Pull request merged**
